site_name: Projeto - Sistema Interno MB/SV
site_description: Documentação interna do sistema
docs_dir: docs
dev_addr: 127.0.0.1:8001

nav:
  - Início: index.md

  - 01 - Projeto:
    - Visão Geral: 01__Projeto/visao-geral.md
    - Tecnologias: 01__Projeto/tecnologias.md
    - Quickstart: 01__Projeto/quickstart.md

  - 02 - Git, GitHub e GitHub Desktop:
    - Branches e Git: 02__GIT_GITHUB_GITHUB_DESKTOP/branches-e-git.md
    - Commits: 02__GIT_GITHUB_GITHUB_DESKTOP/commits.md

  - 03 - Django:
    - Estrutura do Projeto: 03__Django/estrutura-do-projeto.md

  - 04 - Padrões:
    - Comentários e Tags: 04__Padroes/comentarios.md
    
  - 05 - Estrutura Física:
    - Visão Geral: 05__Estrutura_Fisica_do_Projeto/index.md

theme:
  name: material
  language: pt-BR
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    scheme: default
    primary: custom
    accent: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css