# Generated by Django 6.0.6 on 2026-06-26 01:49

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('curva', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_com_boni', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('ipi', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('icms_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('icms_saida_sp', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('icms_saida_media', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pis_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('mva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('st_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('frete_cif_fob', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=8)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peso_cubado', models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('altura'), '*', models.F('largura')), '*', models.F('profundidade')), '/', models.Value(6000)), output_field=models.DecimalField(decimal_places=3, max_digits=8)), output_field=models.DecimalField(decimal_places=3, max_digits=8))),
                ('custo_frete_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custo_frete_ml_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['titulo'],
            },
        ),
    ]
