# Generated by Django 6.0.6 on 2026-06-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_marca_produto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
    ]
