# Generated by Django 6.0.6 on 2026-06-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_cod_fabricante_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cadastrado_erp_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='ultima_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
