# Generated by Django 6.0.6 on 2026-06-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_cadastrado_erp_em_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='armazenagem_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
