# Generated by Django 6.0.6 on 2026-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_armazenagem_planilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='coleta_planilha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_final_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
