# Generated by Django 6.0.6 on 2026-06-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_coleta_planilha_produto_custo_final_planilha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='coleta_planilha',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='custo_final_planilha',
        ),
    ]
