# Generated by Django 6.0.6 on 2026-06-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_remove_produto_coleta_planilha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='custo_frete_ml',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='custo_frete_ml_real',
        ),
    ]
