# Generated by Django 6.0.6 on 2026-06-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('desconto', 'Desconto'), ('acrescimo', 'Acréscimo')], max_length=10)),
                ('valor_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cor', models.CharField(default='#64748b', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tag de Preço',
                'verbose_name_plural': 'Tags de Preço',
                'ordering': ['tipo', 'valor_pct'],
            },
        ),
    ]
