# Generated by Django 6.0.6 on 2026-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ean', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('cod_fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('curva', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('estoque', models.IntegerField(default=0)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_com_boni', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ncm', models.CharField(blank=True, max_length=10, null=True)),
                ('ipi', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('icms_entrada', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('icms_saida_sp', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('icms_saida_media', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('pis_cofins', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('mva', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, null=True)),
                ('st_valor', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('frete_cif_fob', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, null=True)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=8)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['titulo'],
            },
        ),
    ]
