# Generated by Django 6.0.6 on 2026-06-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='frete_cif_fob',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='icms_entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='icms_saida_media',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='icms_saida_sp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ipi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='mva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='pis_cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
