# Generated by Django 6.0.6 on 2026-06-21 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0002_alter_produto_frete_cif_fob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreteML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_min', models.DecimalField(decimal_places=3, max_digits=8)),
                ('peso_max', models.DecimalField(decimal_places=3, max_digits=8)),
                ('preco_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Frete ML',
                'verbose_name_plural': 'Fretes ML',
                'ordering': ['peso_min', 'preco_min'],
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncioML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acrescimo_preco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('meta_margem', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_anuncio', to='precificacao.marketplace')),
            ],
            options={
                'verbose_name': 'Tipo de Anúncio ML',
                'verbose_name_plural': 'Tipos de Anúncio ML',
            },
        ),
    ]
