# Generated by Django 6.0.6 on 2026-06-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0003_freteml_marketplace_tipoanuncioml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freteml',
            name='peso_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
