# Generated by Django 6.0.6 on 2026-06-21 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0004_alter_freteml_peso_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_marketplace', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_envio', models.CharField(choices=[('FLEX', 'Flex'), ('FULL', 'Full')], max_length=10)),
                ('catalogo', models.BooleanField(default=False)),
                ('preco_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_ideal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estoque', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='precificacao.produto')),
                ('tipo_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='precificacao.tipoanuncioml')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['produto', 'tipo_anuncio', 'tipo_envio'],
            },
        ),
    ]
