# Generated by Django 6.0.6 on 2026-06-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0005_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='calculado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoanuncioml',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ConfiguracaoLogisticaML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator_coleta', models.DecimalField(decimal_places=2, default=72, help_text='R$ por metro cúbico (coleta FULL)', max_digits=8)),
                ('armazenagem_diaria', models.DecimalField(decimal_places=4, default=0.015, help_text='R$ por dia (faixa média)', max_digits=8)),
                ('periodo_armazenagem', models.IntegerField(default=30, help_text='Dias de armazenagem a considerar')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('marketplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_logistica', to='precificacao.marketplace')),
            ],
            options={
                'verbose_name': 'Configuração Logística ML',
                'verbose_name_plural': 'Configurações Logísticas ML',
            },
        ),
    ]
