# Generated by Django 6.0.6 on 2026-06-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0004_produto_cadastrado_erp_em_produto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.CharField(max_length=20, unique=True)),
                ('mlbu', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo_anuncio', models.CharField(blank=True, max_length=255, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_anuncio', models.CharField(blank=True, choices=[('gold_special', 'Clássico'), ('gold_pro', 'Premium')], max_length=20, null=True)),
                ('tipo_logistico', models.CharField(blank=True, choices=[('fulfillment', 'FULL'), ('me2', 'Manda tu'), ('flex', 'Flex'), ('drop_off', 'Drop-off')], max_length=20, null=True)),
                ('catalogo', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('closed', 'Fechado')], max_length=10, null=True)),
                ('estoque', models.IntegerField(default=0)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, choices=[('good', 'Bom'), ('regular', 'Regular'), ('bad', 'Ruim')], max_length=10, null=True)),
                ('data_criacao_ml', models.DateTimeField(blank=True, null=True)),
                ('ultima_atualizacao_ml', models.DateTimeField(blank=True, null=True)),
                ('qtd_vendas', models.IntegerField(default=0)),
                ('permalink', models.URLField(blank=True, max_length=500, null=True)),
                ('frete_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frete_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_ml', to='produtos.produto', to_field='sku')),
            ],
            options={
                'verbose_name': 'Anúncio ML',
                'verbose_name_plural': 'Anúncios ML',
                'ordering': ['mlb'],
            },
        ),
    ]
