# Generated by Django 6.0.6 on 2026-06-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDeCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('entrada_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrada_custo_com_boni', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrada_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entrada_frete_cif_fob', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entrada_st_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrada_icms_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entrada_icms_saida_media', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entrada_pis_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entrada_peso', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('entrada_peso_cubado', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('entrada_altura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entrada_largura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entrada_profundidade', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entrada_preco_classico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('entrada_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('entrada_acrescimo_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('entrada_fator_coleta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('entrada_armaz_faixa', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('entrada_periodo_armaz', models.IntegerField(blank=True, null=True)),
                ('formula_metro_cubico', models.CharField(blank=True, default='(Altura ÷ 100) × (Largura ÷ 100) × (Profundidade ÷ 100)', max_length=200)),
                ('calc_metro_cubico', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('formula_custo_final', models.CharField(blank=True, default='Custo c/ Boni + (Custo c/ Boni × IPI) + (Custo c/ Boni × Frete CIF/FOB) + ST Valor', max_length=200)),
                ('calc_custo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_coleta', models.CharField(blank=True, default='Metro Cúbico × Fator de Coleta (apenas FULL)', max_length=200)),
                ('calc_coleta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_armazenagem', models.CharField(blank=True, default='Metro Cúbico × Tarifa de Armazenagem Diária × Período de Armazenagem (apenas FULL)', max_length=200)),
                ('calc_armazenagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_preco_premium', models.CharField(blank=True, default='Preço Clássico × (1 + Acréscimo Premium)', max_length=200)),
                ('calc_preco_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_comissao_classico', models.CharField(blank=True, default='Preço Clássico × Comissão', max_length=200)),
                ('calc_comissao_classico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_comissao_premium', models.CharField(blank=True, default='Preço Premium × Comissão Premium', max_length=200)),
                ('calc_comissao_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_icms_classico', models.CharField(blank=True, default='(Preço Clássico × ICMS Saída) - (Custo × ICMS Entrada)', max_length=200)),
                ('calc_icms_classico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_icms_premium', models.CharField(blank=True, default='(Preço Premium × ICMS Saída) - (Custo × ICMS Entrada)', max_length=200)),
                ('calc_icms_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_pis_cofins_classico', models.CharField(blank=True, default='(Preço Clássico - Custo) × PIS/COFINS', max_length=200)),
                ('calc_pis_cofins_classico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_pis_cofins_premium', models.CharField(blank=True, default='(Preço Premium - Custo) × PIS/COFINS', max_length=200)),
                ('calc_pis_cofins_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formula_margem_classico', models.CharField(blank=True, default='Preço Clássico - Frete - Coleta - Armazenagem - Custo Final - Comissão - ICMS - PIS/COFINS', max_length=500)),
                ('resultado_margem_valor_classico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resultado_margem_pct_classico', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('formula_margem_premium', models.CharField(blank=True, default='Preço Premium - Frete - Coleta - Armazenagem - Custo Final - Comissão Premium - ICMS Premium - PIS/COFINS Premium', max_length=500)),
                ('resultado_margem_valor_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resultado_margem_pct_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('anuncio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_calculo', to='anuncios.anuncioml')),
            ],
            options={
                'verbose_name': 'Base de Cálculo',
                'verbose_name_plural': 'Bases de Cálculo',
            },
        ),
    ]
