# Generated by Django 6.0.6 on 2026-06-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_basedecalculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioml',
            name='margem_real_classico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='margem_real_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_calculado_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_real_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
