# Generated by Django 6.0.6 on 2026-06-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_anuncioml_margem_real_classico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncioml',
            name='margem_real_classico',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='margem_real_premium',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='preco_calculado_premium',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='preco_real_premium',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='entrada_armaz_faixa',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='entrada_comissao',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='entrada_periodo_armaz',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='entrada_preco_classico',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='resultado_margem_pct_classico',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='resultado_margem_pct_premium',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='resultado_margem_valor_classico',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='resultado_margem_valor_premium',
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='margem_classico_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='margem_classico_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='margem_premium_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='margem_premium_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_classico_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_classico_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_premium_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_premium_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='entrada_armazenagem_faixa_valor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='entrada_armazenagem_periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='entrada_comissao_classico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='entrada_preco_classico_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='resultado_margem_classico_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='resultado_margem_classico_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='resultado_margem_premium_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='resultado_margem_premium_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_armazenagem',
            field=models.CharField(blank=True, default='Tarifa Diária da Faixa × Período de Armazenagem', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_coleta',
            field=models.CharField(blank=True, default='Metro Cúbico × Fator de Coleta', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_comissao_classico',
            field=models.CharField(blank=True, default='Preço Clássico Calculado × Comissão Clássico', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_comissao_premium',
            field=models.CharField(blank=True, default='Preço Premium Calculado × Comissão Premium', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_icms_classico',
            field=models.CharField(blank=True, default='(Preço Clássico Calculado × ICMS Saída) - (Custo × ICMS Entrada)', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_icms_premium',
            field=models.CharField(blank=True, default='(Preço Premium Calculado × ICMS Saída) - (Custo × ICMS Entrada)', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_margem_classico',
            field=models.CharField(blank=True, default='Preço Clássico - Frete - Coleta - Armazenagem - Custo Final - Comissão Clássico - ICMS Clássico - PIS/COFINS Clássico', max_length=500),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_pis_cofins_classico',
            field=models.CharField(blank=True, default='(Preço Clássico Calculado - Custo) × PIS/COFINS', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_pis_cofins_premium',
            field=models.CharField(blank=True, default='(Preço Premium Calculado - Custo) × PIS/COFINS', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_preco_premium',
            field=models.CharField(blank=True, default='RoundUpTo90(Preço Clássico Calculado × (1 + Acréscimo Premium))', max_length=200),
        ),
    ]
