# Generated by Django 6.0.6 on 2026-06-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_remove_anuncioml_margem_real_classico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioml',
            name='margem_classico_calculado_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='margem_premium_calculado_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='calc_armazenagem_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='entrada_armazenagem_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='resultado_margem_classico_pct_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='resultado_margem_classico_valor_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='resultado_margem_premium_pct_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='resultado_margem_premium_valor_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_armazenagem',
            field=models.CharField(blank=True, default='[_dinamico] Tarifa Diária da Faixa × Período de Armazenagem', max_length=200),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_margem_classico',
            field=models.CharField(blank=True, default='[_dinamico] Preço Clássico - Frete - Coleta - Armazenagem Dinâmica - Custo Final - Comissão Clássico - ICMS Clássico - PIS/COFINS Clássico', max_length=500),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_margem_premium',
            field=models.CharField(blank=True, default='[_dinamico] Preço Premium - Frete - Coleta - Armazenagem Dinâmica - Custo Final - Comissão Premium - ICMS Premium - PIS/COFINS Premium', max_length=500),
        ),
    ]
