# Generated by Django 6.0.6 on 2026-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_anuncioml_margem_classico_calculado_planilha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioml',
            name='comissao_classico_planilha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='comissao_premium_planilha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='icms_classico_planilha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='icms_premium_planilha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='pis_cofins_classico_planilha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='pis_cofins_premium_planilha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='entrada_coleta_planilha',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basedecalculo',
            name='entrada_custo_final_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
