# Generated by Django 6.0.6 on 2026-06-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_anuncioml_comissao_classico_planilha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncioml',
            name='comissao_classico_planilha',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='comissao_premium_planilha',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='icms_classico_planilha',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='icms_premium_planilha',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='pis_cofins_classico_planilha',
        ),
        migrations.RemoveField(
            model_name='anuncioml',
            name='pis_cofins_premium_planilha',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='entrada_coleta_planilha',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='entrada_custo_final_planilha',
        ),
    ]
