# Generated by Django 6.0.6 on 2026-06-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_remove_anuncioml_comissao_classico_planilha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncioml',
            old_name='frete_real',
            new_name='frete_da_planilha',
        ),
        migrations.RenameField(
            model_name='anuncioml',
            old_name='margem_classico_calculado_planilha',
            new_name='margem_classico_calculado_baseado_na_planilha',
        ),
        migrations.RenameField(
            model_name='anuncioml',
            old_name='margem_classico_real',
            new_name='margem_classico_da_planilha',
        ),
        migrations.RenameField(
            model_name='anuncioml',
            old_name='preco_classico_real',
            new_name='margem_classico_valor_da_planilha',
        ),
        migrations.RenameField(
            model_name='anuncioml',
            old_name='margem_premium_calculado_planilha',
            new_name='margem_premium_calculado_baseado_na_planilha',
        ),
        migrations.RenameField(
            model_name='anuncioml',
            old_name='margem_premium_real',
            new_name='margem_premium_da_planilha',
        ),
        migrations.RenameField(
            model_name='anuncioml',
            old_name='preco_premium_real',
            new_name='margem_premium_valor_da_planilha',
        ),
        migrations.RenameField(
            model_name='basedecalculo',
            old_name='calc_armazenagem_planilha',
            new_name='calc_armazenagem_baseada_na_planilha',
        ),
        migrations.RenameField(
            model_name='basedecalculo',
            old_name='entrada_armazenagem_planilha',
            new_name='entrada_armazenagem_da_planilha',
        ),
        migrations.RenameField(
            model_name='basedecalculo',
            old_name='resultado_margem_classico_pct_planilha',
            new_name='resultado_margem_classico_pct_baseado_na_planilha',
        ),
        migrations.RenameField(
            model_name='basedecalculo',
            old_name='entrada_preco_classico_real',
            new_name='resultado_margem_classico_valor_baseado_na_planilha',
        ),
        migrations.RenameField(
            model_name='basedecalculo',
            old_name='resultado_margem_premium_pct_planilha',
            new_name='resultado_margem_premium_pct_baseado_na_planilha',
        ),
        migrations.RenameField(
            model_name='basedecalculo',
            old_name='resultado_margem_classico_valor_planilha',
            new_name='resultado_margem_premium_valor_baseado_na_planilha',
        ),
        migrations.RemoveField(
            model_name='basedecalculo',
            name='resultado_margem_premium_valor_planilha',
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_classico_da_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_premium_da_planilha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='basedecalculo',
            name='formula_armazenagem',
            field=models.CharField(blank=True, default='Tarifa Diária da Faixa × Período de Armazenagem', max_length=200),
        ),
    ]
