# Generated by Django 6.0.6 on 2026-06-29 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_rename_frete_real_anuncioml_frete_da_planilha_and_more'),
        ('marketplaces', '0003_remove_configuracaologisticaml_armaz_faixa_1_and_more'),
        ('produtos', '0008_remove_produto_custo_frete_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioml',
            name='preco_atacado_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_atacado_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='preco_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CardapioPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_margem_padrao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_margem_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_margem_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferencia_preco', models.CharField(choices=[('margem_padrao', 'Margem Padrão'), ('margem_minima', 'Margem Mínima'), ('margem_maxima', 'Margem Máxima')], default='margem_padrao', max_length=20)),
                ('preco_em_uso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_atacado_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_atacado_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculado_em', models.DateTimeField(auto_now=True)),
                ('valido', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio_precos', to='produtos.produto', to_field='sku')),
                ('tipo_anuncio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cardapio_precos', to='marketplaces.tipoanuncioml')),
            ],
            options={
                'verbose_name': 'Cardápio de Preços',
                'verbose_name_plural': 'Cardápios de Preços',
                'ordering': ['produto', 'tipo_anuncio'],
                'unique_together': {('produto', 'tipo_anuncio')},
            },
        ),
    ]
