# Generated by Django 6.0.6 on 2026-06-29 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0009_anuncioml_preco_atacado_2_anuncioml_preco_atacado_3_and_more'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncioml',
            old_name='preco_manual',
            new_name='preco_travado',
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='tag_preco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to='tags.tagpreco'),
        ),
    ]
