# Generated by Django 6.0.6 on 2026-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0010_rename_preco_manual_anuncioml_preco_travado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncioml',
            name='catalog_listing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='catalog_product_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='item_relations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anuncioml',
            name='sku_ml',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='anuncioml',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('closed', 'Encerrado'), ('under_review', 'Em revisão'), ('payment_required', 'Débito pendente'), ('not_yet_active', 'Aguardando ativação')], max_length=20, null=True),
        ),
    ]
