# Generated by Django 6.0.6 on 2026-06-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoLogisticaML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator_coleta', models.DecimalField(decimal_places=2, default=72, max_digits=8)),
                ('periodo_armazenagem', models.IntegerField(default=30)),
                ('armaz_faixa_1', models.DecimalField(decimal_places=4, default=0.007, max_digits=8)),
                ('armaz_faixa_2', models.DecimalField(decimal_places=4, default=0.015, max_digits=8)),
                ('armaz_faixa_3', models.DecimalField(decimal_places=4, default=0.05, max_digits=8)),
                ('armaz_faixa_4', models.DecimalField(decimal_places=4, default=0.107, max_digits=8)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('marketplace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_logistica', to='marketplaces.marketplace')),
            ],
            options={
                'verbose_name': 'Configuração Logística ML',
                'verbose_name_plural': 'Configurações Logísticas ML',
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncioML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_anuncio', models.CharField(choices=[('gold_special', 'Clássico'), ('gold_pro', 'Premium')], max_length=20)),
                ('tipo_logistico', models.CharField(choices=[('fulfillment', 'FULL'), ('flex', 'Flex'), ('me2', 'Padrão')], max_length=20)),
                ('catalogo', models.BooleanField(default=False)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acrescimo_preco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margem_padrao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margem_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margem_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desconto_atacado_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('desconto_atacado_3', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_anuncio', to='marketplaces.marketplace')),
            ],
            options={
                'verbose_name': 'Tipo de Anúncio ML',
                'verbose_name_plural': 'Tipos de Anúncio ML',
                'ordering': ['marketplace', 'tipo_anuncio', 'tipo_logistico'],
            },
        ),
    ]
