# Generated by Django 6.0.6 on 2026-06-28 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaArmazenagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_diario', models.DecimalField(decimal_places=4, max_digits=8)),
                ('max_altura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_largura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_profundidade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faixas_armazenagem', to='marketplaces.marketplace')),
            ],
            options={
                'verbose_name': 'Faixa de Armazenagem',
                'verbose_name_plural': 'Faixas de Armazenagem',
                'ordering': ['marketplace', 'ordem'],
            },
        ),
    ]
