# Generated by Django 6.0.6 on 2026-06-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0002_faixaarmazenagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaologisticaml',
            name='armaz_faixa_1',
        ),
        migrations.RemoveField(
            model_name='configuracaologisticaml',
            name='armaz_faixa_2',
        ),
        migrations.RemoveField(
            model_name='configuracaologisticaml',
            name='armaz_faixa_3',
        ),
        migrations.RemoveField(
            model_name='configuracaologisticaml',
            name='armaz_faixa_4',
        ),
    ]
